---
title: "SEMFC Usecase"
output: html_notebook
---




# SEMFC USECASE





```{r}


source("tests/testthat/dataset_configs/load_configs.R")
source("inst/report/report_utils.R")

library(devtools)
load_all()
library(MASS)
library(mvtnorm)
remotes::install_github("yrosseel/lavaan")
library(lavaan)
```


## SIMULATED DATA


### ALL REFLECTIVE


```{r}
source('inst/simulations/data_simulation_reflective.R')

set.seed(20091979)
N <- 300

X <- mvrnorm(N, rep(0, 18), SIGMA, empirical = FALSE)
colnames(X) <- paste("X", rep(1:6, each = 3), rep(1:3, 6), sep ="")


Y <- list(LV1 = X[, 1:3], LV2 = X[, 4:6], LV3 = X[, 7:9],
         LV4 = X[, 10:12], LV5 = X[, 13:15], LV6 = X[, 16:18])



C <- matrix(c(0, 0, 0, 0, 1, 0,
             0, 0, 0, 0, 1, 0,
             0, 0, 0, 0, 0, 1,
             0, 0, 0, 0, 0, 1,
             0, 0, 0, 0, 0, 1,
             0, 0, 0, 0, 1, 0), 6, 6, byrow = TRUE)

colnames(C) <- rownames(C) <- names(Y)

mode <- rep("reflective", 6)


source('inst/model/model_reflective.R')

Y <- Y_2
X <- X_2


```

```{r}
cat(sem.model)
```


```{r}
model <- SemFC$new(data=Y, relation_matrix = C, mode=mode, estimator = "svd")
model$fit(infer = T, B = 100)
est = model$parameterEstimates(standardized = T)

modelml <- SemFC$new(data=Y, relation_matrix = C, mode=mode, estimator = "ml")
modelml$fit(infer = T, tol = 1e-8)
est_ml = modelml$parameterEstimates(standardized = T)
```



```{r}
modelml$summary(standardized = T)
```




```{r}
lavaan_ml <- sem(sem.model,
               data = X,
                       estimator = "ML",
                       likelihood = "wishart")

lavaan_results <- parameterEstimates(lavaan_ml, standardized = TRUE)

lavaan_ml


```



```{r}
lavInspect(lavaan_ml)
```



#### Comparison of estimates between ML and lavaan

```{r}
print(merge_estimates_with_lavaan(est_ml, lavaan_results))
```


#### Comparison of estimates between SVD, ML and lavaan


```{r}
print(merge_estimates(est_ml, est, lavaan_results))
```




### FACTORS AND COMPOSITES




```{r}
source('inst/simulations/data_simulation_mixed.R')


set.seed(20091979)
N <- 300

X <- mvrnorm(N, rep(0, 18), SIGMA, empirical = FALSE)
colnames(X) <- paste("X", rep(1:6, each = 3), rep(1:3, 6), sep ="")


Y <- list(LV1 = X[, 1:3], LV2 = X[, 4:6], LV3 = X[, 7:9],
         LV4 = X[, 10:12], LV5 = X[, 13:15], LV6 = X[, 16:18])

mode <- c(rep("formative", 4), rep("reflective", 2))

C <- matrix(c(0, 0, 0, 0, 1, 0,
             0, 0, 0, 0, 1, 0,
             0, 0, 0, 0, 0, 1,
             0, 0, 0, 0, 0, 1,
             0, 0, 0, 0, 0, 1,
             0, 0, 0, 0, 1, 0), 6, 6, byrow = TRUE)
```





```{r}
source('inst/model/model_mixed.R')

Y <- Y_2
X <- X_2

cat(sem.model)
```

```{r}


lavaan_composite <- sem(sem.model,
               data = X,
                       estimator = "ML",
                       likelihood = "wishart")

lavaan_results_composite <- parameterEstimates(lavaan_composite, standardized = TRUE)

```


```{r}
model <- SemFC$new(data=Y, relation_matrix = C, mode=mode, estimator = "svd")
model$fit(infer = T, B = 100)
estfc = model$parameterEstimates(standardized = T)

modelml <- SemFC$new(data=Y, relation_matrix = C, mode=mode, estimator = "ml")
modelml$fit(infer = T, tol = 1e-8)
est_mlfc = modelml$parameterEstimates(standardized = T)
```

```{r}
print(merge_estimates_with_lavaan(est_mlfc, lavaan_results_composite))
```



```{r}
print(merge_estimates(est_mlfc, estfc, lavaan_results_composite))
```




```{r}
model$summary(standardized = T)
```


#### Comparison of estimates between SVD, ML FC and lavaan Factors

```{r}
print(merge_estimates(est_mlfc, estfc, lavaan_results))
```



#### ESTIMATES RESULTS



```{r}
print(model$get_estimate('psi'))
```

```{r}
print(model$get_estimate('beta'))
```



```{r}
print(model$get_estimate('gamma'))
```



```{r}
print(model$get_estimate('lambda'))
```



```{r}
est
```


## PoliticalDemocracy DATA

```{r}

get_dataset_config <- function(dataset_name, dataset = NULL) {

  config <- DATASETS_CONFIG[[dataset_name]]
  func <- get(config$config_func)


  if (config$is_generated) {
    return(func())
  } else {
    return(func(dataset))
  }
}
```


```{r}
dataset_name = 'PoliticalDemocracy'
dataset <- load_dataset_data(dataset_name)
config <- get_dataset_config(dataset_name, dataset)

svd_results <- fit_and_get_estimates(config, "svd", list(B = 100))
ml_results <- fit_and_get_estimates(config, "ml", list(tol = 1e-8))
lavaan_ml <- sem(config$sem,
               data = data.frame(Reduce("cbind", config$data)),
                       estimator = "ML",
                       likelihood = "wishart")
lavaan_results <- parameterEstimates(lavaan_ml, standardized = TRUE)
```

```{r}
cat(config$sem)
```


```{r}
print(merge_estimates_with_lavaan(ml_results$param, lavaan_results))
```




```{r}
ml_results$param[] <- lapply(ml_results$param, function(x) if (is.numeric(x)) round(x, 3) else x)
ml_results$param
```
```{r}
svd_results$param[] <- lapply(svd_results$param, function(x) if (is.numeric(x)) round(x, 3) else x)
svd_results$param
```


```{r}
lavaan_results
```